defaults:
  - task_config: adder

model_type: TF_LENS
dataset_type: 'dihedral'

llc: false
ed: true
form: false
use_logits: true

run_idx: 0
wandb_project_name: devinterp-automata
entity_name: wu-cindyx

lr: 1e-4
num_training_iter: 14000
early_stop_patience: 10
early_stop_smoothing_window: 5
early_stop_acc_threshold: 99.9
truncate_its: null # Set to null if you want to automatically truncate using above settings

n_layers: 3
seq_len: 25

rlct_config:
  sampling_method: SGLD_MA
  rlct_loss_type: ce # When not using distill kl loss
  num_chains: 5
  num_draws: 5000
  num_burnin_steps: 0 
  num_steps_bw_draws: 1
  cores: 1
  seed: null

  use_diagnostics: true
  online: false
  verbose: true
  use_distill_loss: true

  ed_config:
    batches_per_checkpoint: 300
    eval_frequency: 10

  sgld_kwargs:
    lr: 5e-8
    noise_level: 1.0
    weight_decay: 5e-8
    elasticity: 10
    temperature: adaptive
    num_samples: 10000 # True value set at run-time.
    bounding_box_size: 0.5
    mh_frequency: 10

  rlct_model_save_dir: null
  rlct_data_dir: null

ed_plot_config:
  transitions: null
  colors: null  # Example: [[255, 0, 0], [0, 255, 0], [0, 0, 255]]
  num_pca_components: 3
  plot_caustic: true
  figsize: [20, 6]
  marked_cusp_data: null
  use_cache: false
  num_sharp_points: 10
  num_vertices: 30
  osculate_start: 1
  osculate_end_offset: 0
  osculate_skip: 10
  smoothing_sigma_early: 10
  smoothing_sigma_late: 20
  smoothing_late_boundary: 100
  show_vertex_influence: false
  ed_folder: ed_data